### ISSUE TITLE
Hidding breakpoint on wrapper bug

### ISSUE THREAD

**Issue by EmerickH** [PadmaUnlimited/padma-theme#2]
Hello,
First I recently discovered Padma and I'm actually very surprised that it's not that known because it's absolutely fantastic!
While creating a template I discovered a very annoying bug: if you configure a breakpoint on a wrapper to hide the block on a certain width like this:
![image](https://user-images.githubusercontent.com/21125429/74594528-f316c300-5037-11ea-8fa2-31284c7f2945.png)
The wrapper is also hidden in the Visual Editor!
And so the only way to edit it is to stretch the browser (almost impossible to do if it's a mobile width), or use developer tools to disable the CSS property:
![image](https://user-images.githubusercontent.com/21125429/74594586-76d0af80-5038-11ea-9243-3a137b78155f.png)
(I created a small Tampermonkey script to temporary be able to edit my template https://gist.github.com/EmerickH/78873613273a2b357d1849629eefa3e5)
Also it would be very nice to be able to be able to configure breakpoints on the styling tab: ex be able to change font size for the mobile version.

Thank you,
Emerick

**Comment by marodok** [comment]
Hi Emerick,  It's great you like Padma so much. 

There is a plan to add better Responsive control over the design mode (we call it "visual media queries") and we will try to get it ready for the 1.3 version.

There is a roadmap: https://trello.com/b/MgFeEsey/padma-unlimited-roadmap 

Thanks for this report, I'll add this issue to be checked into the roadmap

**Comment by marodok** [comment]
Hi Emerick,

We added an option Padma Theme > Optoins > Visual Editor > Show hidden wrappers on design mode

![image](https://user-images.githubusercontent.com/18367936/76652046-64f50600-652b-11ea-882f-3b6b57e46e55.png)

This will prevent to hide the wrappers in the visual editor when the preview is mobile. The wrapper will look like this:

![image](https://user-images.githubusercontent.com/18367936/76652170-a4235700-652b-11ea-8b2f-1d300710bc27.png)

Could you test this?
